"""Sprite sheet loader and frame animator with 5-direction support."""

from __future__ import annotations

import math
from pathlib import Path
from typing import Any

import structlog

log = structlog.get_logger("assistant.pet.sprite")

ANIMATIONS = ("idle", "walk", "type", "run", "sad", "sleep")
# 5 directions (left variants auto-generated by horizontal flip):
#   side        = moving horizontally (E/W)
#   front       = moving straight toward viewer (S)
#   back        = moving straight away from viewer (N)
#   front_side  = diagonal toward viewer (SE/SW)
#   back_side   = diagonal away from viewer (NE/NW)
DIRECTIONS = ("side", "front", "back", "front_side", "back_side")
PET_TYPES = ("dog", "cat", "robot", "fox", "owl")
DEFAULT_FRAME_SIZE = 96
DEFAULT_FPS = 6


def angle_to_direction(dx: float, dy: float) -> str:
    """Convert movement delta to the best sprite direction (5-way).

    Uses abs(dx) so left/right is handled by horizontal flip, not separate sprites.
    Angle zones (from horizontal):
      -90 to -55  → back         (moving up/away)
      -55 to -15  → back_side    (diagonal up)
      -15 to +15  → side         (horizontal)
      +15 to +55  → front_side   (diagonal down)
      +55 to +90  → front        (moving down/toward viewer)
    """
    if abs(dx) < 0.01 and abs(dy) < 0.01:
        return "side"
    angle = math.degrees(math.atan2(dy, abs(dx)))
    if angle > 55:
        return "front"
    elif angle > 15:
        return "front_side"
    elif angle < -55:
        return "back"
    elif angle < -15:
        return "back_side"
    return "side"


class SpriteEngine:
    """Loads sprite sheets and provides frame-by-frame animation data.

    Supports multiple naming conventions (checked in order):
    1. Full 5-direction:  walk_side.png, walk_front.png, walk_back.png,
                          walk_front_side.png, walk_back_side.png
    2. 3-direction:       walk_side.png, walk_front.png, walk_back.png
                          (diagonals fall back to nearest: front_side→front, back_side→back)
    3. Legacy single:     walk.png  (used for all directions)
    """

    def __init__(self, pet_type: str, assets_dir: str | None = None, frame_size: int = DEFAULT_FRAME_SIZE) -> None:
        if pet_type not in PET_TYPES:
            raise ValueError(f"Unknown pet type: {pet_type!r}. Must be one of {PET_TYPES}")
        self._pet_type = pet_type
        self._frame_size = frame_size

        if assets_dir is None:
            assets_dir = str(Path(__file__).parent / "assets")
        self._assets_dir = Path(assets_dir) / pet_type

        # sheets[anim][direction] = QPixmap
        self._sheets: dict[str, dict[str, Any]] = {}
        self._frame_counts: dict[str, dict[str, int]] = {}
        self._current_animation = "idle"
        self._current_direction = "side"
        self._current_frame = 0
        self._has_directions = False
        self._loaded = False

    @property
    def pet_type(self) -> str:
        return self._pet_type

    @property
    def current_animation(self) -> str:
        return self._current_animation

    @property
    def current_direction(self) -> str:
        return self._current_direction

    @property
    def frame_size(self) -> int:
        return self._frame_size

    @property
    def has_directions(self) -> bool:
        return self._has_directions

    def load(self) -> bool:
        """Load all sprite sheets. Returns True if at least idle loaded."""
        try:
            from PyQt6.QtGui import QPixmap
        except ImportError:
            log.warning("sprite.pyqt6_not_available")
            return False

        loaded_any = False
        for anim in ANIMATIONS:
            self._sheets[anim] = {}
            self._frame_counts[anim] = {}

            # Try all 5 directions
            for direction in DIRECTIONS:
                path = self._assets_dir / f"{anim}_{direction}.png"
                if path.is_file():
                    pixmap = QPixmap(str(path))
                    if not pixmap.isNull():
                        frame_count = max(1, pixmap.width() // self._frame_size)
                        self._sheets[anim][direction] = pixmap
                        self._frame_counts[anim][direction] = frame_count
                        loaded_any = True
                        self._has_directions = True

            # Fallback: legacy single file (e.g. walk.png → side)
            if "side" not in self._sheets[anim]:
                path = self._assets_dir / f"{anim}.png"
                if path.is_file():
                    pixmap = QPixmap(str(path))
                    if not pixmap.isNull():
                        frame_count = max(1, pixmap.width() // self._frame_size)
                        self._sheets[anim]["side"] = pixmap
                        self._frame_counts[anim]["side"] = frame_count
                        loaded_any = True

        self._loaded = loaded_any
        if loaded_any:
            anim_list = [a for a in ANIMATIONS if self._sheets.get(a)]
            log.info("sprite.loaded", pet_type=self._pet_type,
                     animations=anim_list, multi_direction=self._has_directions)
        else:
            log.warning("sprite.no_sheets_loaded", pet_type=self._pet_type)
        return loaded_any

    def set_animation(self, name: str) -> None:
        """Switch to a different animation. Resets frame counter."""
        if name not in ANIMATIONS:
            name = "idle"
        if name not in self._sheets or not self._sheets[name]:
            name = "idle"
        if name != self._current_animation:
            self._current_animation = name
            self._current_frame = 0

    def set_direction(self, direction: str) -> None:
        if direction in DIRECTIONS:
            self._current_direction = direction

    def set_direction_from_movement(self, dx: float, dy: float) -> None:
        self._current_direction = angle_to_direction(dx, dy)

    def _resolve_direction(self, anim: str, direction: str) -> str:
        """Find the best available direction sprite, with fallback chain."""
        anim_sheets = self._sheets.get(anim, {})
        if direction in anim_sheets:
            return direction
        # Fallback chain for diagonals
        fallbacks = {
            "front_side": ["front", "side"],
            "back_side": ["back", "side"],
            "front": ["front_side", "side"],
            "back": ["back_side", "side"],
            "side": ["front_side", "back_side", "front", "back"],
        }
        for fb in fallbacks.get(direction, []):
            if fb in anim_sheets:
                return fb
        # Last resort: any available
        if anim_sheets:
            return next(iter(anim_sheets))
        return "side"

    def get_current_frame(self) -> Any:
        """Return the current frame as a QPixmap crop of the sprite sheet."""
        if not self._loaded:
            return None

        anim = self._current_animation
        if anim not in self._sheets or not self._sheets[anim]:
            anim = "idle"
            if anim not in self._sheets or not self._sheets[anim]:
                return None

        direction = self._resolve_direction(anim, self._current_direction)
        sheet = self._sheets[anim][direction]
        frame_count = self._frame_counts[anim][direction]
        frame_idx = self._current_frame % frame_count
        x = frame_idx * self._frame_size

        return sheet.copy(x, 0, self._frame_size, self._frame_size)

    def advance_frame(self) -> None:
        anim = self._current_animation
        if anim in self._frame_counts and self._frame_counts[anim]:
            direction = self._resolve_direction(anim, self._current_direction)
            if direction in self._frame_counts[anim]:
                count = self._frame_counts[anim][direction]
                self._current_frame = (self._current_frame + 1) % count

    def get_available_animations(self) -> list[str]:
        return [a for a in ANIMATIONS if self._sheets.get(a)]

    def is_loaded(self) -> bool:
        return self._loaded
